packages:
  - 'packages/*'

minimumReleaseAge: 2880 # 2 days, see: https://pnpm.io/settings#minimumreleaseage

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - nx

ignoredBuiltDependencies:
  - keytar
