packages:
  - 'packages/*'

minimumReleaseAge: 2880 # 2 days, see: https://pnpm.io/settings#minimumreleaseage

allowBuilds:
  '@vscode/vsce-sign': true
  nx: true
  keytar: false
  unrs-resolver: false
